CREATE  TABLE IF NOT EXISTS `member` (
  `member_orl` BIGINT(11) NOT NULL AUTO_INCREMENT ,
  `user_id` VARCHAR(100) NOT NULL ,
  `user_name` VARCHAR(100) NOT NULL ,
  `nickname` VARCHAR(100) NOT NULL ,
  `password` VARCHAR(250) NOT NULL ,
  `temp_password` VARCHAR(250) NULL ,
  `email` VARCHAR(250) NOT NULL ,
  `email_id` VARCHAR(100) NOT NULL ,
  `email_host` VARCHAR(100) NOT NULL ,
  `memo` TEXT NULL ,
  `is_admin` CHAR(1) NULL DEFAULT 'N' ,
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '-2 : 탈퇴 , -1 : 정지 , 0 : 일반' ,
  `sid` VARCHAR(250) NOT NULL ,
  `login_sid` VARCHAR(250) NULL ,
  `login_datetime` CHAR(14) NULL ,
  `login_ipaddress` VARCHAR(128) NULL ,
  `reg_datetime` CHAR(14) NULL ,
  `update_datetime` CHAR(14) NULL ,
  `listorder` BIGINT(11) NULL ,
  PRIMARY KEY (`member_orl`) ,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) ,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) )
ENGINE = InnoDB