CREATE  TABLE IF NOT EXISTS `document` (
  `document_orl` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판 ORL' ,
  `module_orl` BIGINT(11) NOT NULL ,
  `subject` VARCHAR(250) NOT NULL COMMENT '제목' ,
  `is_notice` CHAR(1) NULL DEFAULT 'N' ,
  `is_bold` CHAR(1) NULL DEFAULT 'N' ,
  `color` CHAR(6) NULL ,
  `style` VARCHAR(250) NULL ,
  `content` LONGTEXT NOT NULL COMMENT '내용' ,
  `content_text` LONGTEXT NOT NULL ,
  `member_orl` BIGINT(11) NOT NULL ,
  `user_id` VARCHAR(100) NOT NULL COMMENT '등록자 ID' ,
  `nickname` VARCHAR(100) NOT NULL COMMENT '등록자 닉네임' ,
  `readed_count` BIGINT(11) NULL DEFAULT 0 ,
  `file_count` BIGINT(11) NULL DEFAULT 0 ,
  `comment_count` BIGINT(11) NULL DEFAULT 0 ,
  `good_count` BIGINT(11) NULL DEFAULT 0 ,
  `bad_count` BIGINT(11) NULL DEFAULT 0 ,
  `accuse_count` BIGINT(11) NULL DEFAULT 0 COMMENT '신고 횟수' ,
  `is_mobile` CHAR(1) NULL DEFAULT 'N' ,
  `state` TINYINT(1) NULL DEFAULT 0 COMMENT '글상태' ,
  `reg_datetime` CHAR(14) NULL ,
  `update_datetime` CHAR(14) NULL ,
  `ipaddress` VARCHAR(128) NOT NULL ,
  `listorder` BIGINT(11) NULL ,
  PRIMARY KEY (`document_orl`) ,
  INDEX `idx_listorder` (`listorder` ASC) )
ENGINE = InnoDB
COMMENT = '게시판'